config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'welcome/index'
  root 'welcome#index'
  concern :partable do
    resources :parts
  end
  resources :users do
    resources :exams do
      resources :subjects do
        resources :chapters do


        end
      end
    end

  end
  resources :patterns, concerns: :partable

  resources :problems, concerns: :partable
  get '/debugs' , to:"debugs#index"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'problemsfront' => 'problems#front'
  post 'mark' => 'problems#mark', as:'mark'
  get 'list' => 'list#index'
  get 'list2' => 'list#index2'
  get 'list3' => 'list#index3'
  get 'list4' => 'list#index4'
  get 'list5' => 'list#index5'
  get 'list6' => 'list#index6'
  get 'tree' => 'list#tree'
  get 'levels' => 'levels#index'
  post '/exam_update' => 'debugs#update', as: 'exam_update'
  post '/exam_generate' => 'debugs#generate', as: 'exam_generate'
  post '/exam_destroy' => 'debugs#destroy', as: 'exam_destroy'
  get '/status' => 'debugs#status'
  get '/start/:selected_test_id' =>'problems#set', as: 'exam_start'
  get '/recommend' =>'problems#recommend'
  get '/solution' =>'debugs#solution'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :groups
  belongs_to :subject

end

app/models/dic_chapter.rb
class DicChapter < ApplicationRecord
  has_many :dic_groups
  belongs_to :dic_subject
end

app/models/dic_group.rb
class DicGroup < ApplicationRecord
  belongs_to :dic_chapter
end

app/models/dic_subject.rb
class DicSubject < ApplicationRecord
  has_many :dic_chapters

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :subjects
  belongs_to :user
  has_many :meters
  has_many :history_problems





end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :chapter
end

app/models/history_problem.rb
class HistoryProblem < ApplicationRecord
  belongs_to :exam
end

app/models/last_exam.rb
class LastExam < ApplicationRecord
  belongs_to :user
end

app/models/meter.rb
class Meter < ApplicationRecord
  belongs_to :exam

  def set_score(diff)
    if(self.sign == 0 )
      self.sign = diff
      self.combo =1
    elsif self.sign*diff>0
      self.combo *= 1.25
    else
      self.combo =1
      self.sign =diff
    end

    self.score += 0.7*self.combo*diff

    if(self.score>5)
      self.score =5
    elsif self.score <-5
      self.score = -5
    end
    self.save
    self.exam.save


  end
  def first
    return self
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :pattern
  belongs_to :problem
end

app/models/pattern.rb
class Pattern < ApplicationRecord

  has_many :parts
  has_many :problems, through: :parts


end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :parts
  has_many :patterns, through: :parts


end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :chapters
  belongs_to :exam


end

app/models/user.rb
class User < ApplicationRecord
  has_many :exams
  validates :username, presence:true, uniqueness: true
  validates :password, presence:true
  validates :password_confirmation, presence: true
  has_secure_password
  has_one :last_exam


  def set_last_exam(id)
    self.last_exam=id
    self.save

  end

  def generate_exam()


    new_exam = Exam.new(user: self, name: '새로운 시험')

    self.exams << new_exam
    dic_subjects=DicSubject.all
    dic_subjects.each do |dic_subject|
      subject = Subject.create(name: dic_subject.name, exam: new_exam,onStudy: 0, onExam: 0)

      dic_subject.dic_chapters.each do |dic_chapter|
        chapter = Chapter.create(name:dic_chapter.name, subject: subject, onStudy:0, onExam:0, level:0)

        dic_chapter.dic_groups.each do |dic_group|
          group = Group.create(name:dic_group.name, chapter:chapter, level:0)

        end
      end
    end





    new_exam.save

    self.save
  end



 end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  def index
    @problems = Problem.all
  end

  def recommend
    puts !session[:user_id]
    if(!session[:user_id])
      puts 'hi'
      redirect_to '/login'

    else
      @user = User.find(session[:user_id])

      if(@user.last_exam)
        @exam = @user.exams.find(@user.last_exam.exam_id)

        @problems =[]
        @groups = []

        @exam.subjects.each do |subject|
          subject.chapters.each do |chapter|
            if chapter.onStudy
              @problems += Problem.all.where( chapter_name: chapter.name )
              @groups +=chapter.groups
            end
          end
        end

        score_minimum= @groups[0].level
        recommend_group =@groups[0]
        @groups.each do |group|
          if score_minimum > group.level
            score_minimum = group.level
            recommend_group = group
          end
        end

        if score_minimum<-2
          recommend_diff = 1
        elsif score_minimum < 2
          recommend_diff =2
        else
          recommend_diff =3
        end

        recommend_pattern =Pattern.find_by(name: recommend_group.name)
        recommend_problems = recommend_pattern.problems.where(difficulty: recommend_diff)
        recommend_problems.each do |pb|
          if ! @exam.history_problems.find_by(problem_id:pb.id) && pb.prev_problem =='NaN'
            @recommend_problem = pb
            break
          end

        end

        if !@recommend_problem
          recommend_pattern.problems.each do |pb|
            if ! @exam.history_problems.find_by(problem_id:pb.id) && pb.prev_problem =='NaN'
              @recommend_problem = pb
              break
            end
          end
        end

        if !@recommend_problem
          @problems.each do |pb|
            if ! @exam.history_problems.find_by(problem_id:pb.id) && pb.prev_problem =='NaN'
              @recommend_problem = pb
              break
            end
          end
        end

        if @recommend_problem
          redirect_to problem_path(@recommend_problem)
        end
      else
        redirect_to '/list6'

      end





    end



  end

  def set
    puts "hi"
    user = User.find( session[:user_id] )
    if !last_exam=user.last_exam
      last_exam = LastExam.create(user: user, exam_id:params[:selected_test_id].to_i)
    end
    last_exam.exam_id = params[:selected_test_id].to_i
    last_exam.save

    user.save


    redirect_to '/recommend'

  end
  def next
    @problem = Problem.find(params[:problem_id])
    redirect_to problem_path(@problem)
  end


  def show
    if(session[:user_id])
      @problem = Problem.find(params[:id])
      @patterns = @problem.patterns
      @user = User.find(session[:user_id])
      if(@user.last_exam)
        @exam = Exam.find(@user.last_exam.exam_id)
      else
        redirect_to '/recommend'
      end

    else
      redirect_to '/login'
    end



  end


  def mark

    @user = User.find(params[:user_id])
    @exam = @user.exams.find(params[:exam_id])


    @groups = []

    @exam.subjects.each do |subject|
      subject.chapters.each do |chapter|
        if chapter.onExam
          @groups +=chapter.groups
        end
      end
    end



    @problem =Problem.find(params[:problem_id])
    result = params[:result]
    puts result

    if result=='1'
      diff = @problem.difficulty
      puts 'true'
    else
      diff = -(4-@problem.difficulty)
      puts 'false'
    end
    puts diff

    if last_problem = @exam.history_problems.find_by(problem_id: @problem.id)
    else
      last_problem = HistoryProblem.new(exam: @exam, problem_id: @problem.id, correct: false)
      @problem.patterns.each do |pattern|
        if meter = @exam.meters.find_by(pattern_name:pattern.name)
        else
          meter = Meter.new(score: 0, combo:1, sign:0, pattern_name: pattern.name, exam: @exam)
          meter.save
          @exam.save
        end
        meter.set_score(diff)

        @groups.each do |group|
          if group.name == pattern.name
            group.level = meter.score
            group.save
          end
        end

      end

    end

    if diff>0
      last_problem.correct = true
    else
      last_problem.correct = false
    end

    last_problem.save
    last_problem.exam.save



    #self.recommend




  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/debugs_helper.rb
module DebugsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
  def index
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/problems/index.html.erb
<h2>problems list</h2>
<% @problems.each do |problem| %>
<div>
  <h3>name:
    <%= problem.name %></h3>
  <p>difficulty:
    <%= problem.difficulty %></p>
  <%= link_to "view more ", problem_path(problem)%>

</div>
<% end %>

<div>
  <%= link_to "patterns list", patterns_path %>
</div>

app/views/problems/recommend.html.erb
<div id="default_page">
  <img src="" alt="Three Deers">
  <p>문제를 다 푸셨군요! 학습 범위를 늘려보세요!</p>
</div>

<script type="text/javascript">
$(document).ready(function(){
  default_page();

})
function default_page(){
  $('#default_page img').attr("src",function(){
    var ran_num=Math.floor((Math.random() * 3) + 1);
    return "/img/logos/deer3/0"+ran_num+".png";
  })
}
</script>

app/views/problems/show.html.erb
<%= stylesheet_link_tag "problems.css" %>
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
<%= javascript_include_tag "/assets/nerdamer/nerdamer.core" %>
<%= javascript_include_tag "/assets/nerdamer/Algebra" %>
<%= javascript_include_tag "/assets/nerdamer/Calculus" %>
<%= javascript_include_tag "/assets/nerdamer/Solve" %>
<%= javascript_include_tag "/assets/nerdamer/Extra" %>
<script type="text/javascript" charset="utf-8">
    nerdamer.getCore().PARSER.constants['E'] = 'E';



</script>
<div class="row" style="margin-top: 3vh;">
  <div class="col s10" style="margin-left:6.25vw;margin-right:3vw;">
    <div id = "problem_number">
      <!-- <ox></ox> -->
      <text></text>
      <script type="text/javascript">
        var problem_number= '<%=@problem.name%>';
        problem_number=problem_number.slice(1);
        $('#problem_number text').text(problem_number);
      </script>
    </div>
  </div>
  <div class="col s6" style="width: 41.67vw;margin-left:6.25vw;margin-right:2.08vw;padding:0;">
    <div class="row">
      <div class="image_box box_shadow" id="problem_box">
        <div class="scroll_problem " id="problem_text">
          <div>
            <%=raw @problem.problem_html%>
          </div>

        </div>
      </div>
    </div>

  </div>
  <div class="col s6"style="width: 41.67vw;margin-right:0;margin-left:2.08vw;padding:0;">
    <div class="image_box box_shadow" id="answer_box">

      <div class="scroll_problem ">
        <div id = "answer_converted">답안  </div>
        <div id = "solution" style = "display: none;">
          <%= @problem.solution_html%>

        </div>
      </div>
    </div>
    <!-- <div class="row">
      <div class="row">
        <div class="col s12 round_button box_shadow">
          <text id = "answer_converted">답안  </text>
        </div>
      </div>
    </div> -->
    <!-- <%= form_for(:mark, url: mark_path(@problem, ) )do |f| %> -->
    <div class="row">
      <div class="col s8 round_button box_shadow"id="input_box" >
        <!-- 이렇게하면 영문만(숫자포함) 입력 됨 //이메일 아이디 같은거 입력을 만들때 -->
        <!-- <%= f.text_field :user_answer, :placeholder => '수 식  입 력', id:"textarea", :onchange =>'fn_press_han(this)', autocomplete:"off" %> -->
        <input type="text" id="textarea" autocomplete="off" placeholder="수 식  입 력" onchange="fn_press_han(this)">
      </div>
      <div class="col s4">
        <span class= "round_button box_shadow" id = "submit_button">제 출</span>
          <!-- <%= f.submit '제  출', class:" round_button box_shadow", id:"submit_button" %> -->
      </div>
    </div>
    <!-- <% end%> -->
    <div class="col s6" style="padding-left:0;"><div class="round_button box_shadow brownish_box_shadow disabled_button" id="see_answer" style="width: 100%;">풀  이  보  기</div></div>
    <div class="col s6" style="padding-right:0;"><div class="round_button box_shadow brownish_box_shadow disabled_button" id="next_problem"style="width: 100%;">다 음  문 제</div></div>
  </div>
</div>

  </div>


</div>

<script>

var tried_solving = false;
function fn_press_han(obj)
{
    //좌우 방향키, 백스페이스, 딜리트, 탭키에 대한 예외
    if(event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 37 || event.keyCode == 39
    || event.keyCode == 46 ) return;
    //obj.value = obj.value.replace(/[\a-zㄱ-ㅎㅏ-ㅣ가-힣]/g, '');
    obj.value = obj.value.replace(/[\ㄱ-ㅎㅏ-ㅣ가-힣]/g, '');
};
var DynamicMJ = {
  formula: document.getElementById("answer_converted"),

  update: function () {
    var user_answer = document.getElementById("textarea").value;
    var make = nerdamer(user_answer).toTeX();
    make=make.replace('epsilon_0','\\epsilon_0');
    make=make.replace('mu_0','\\mu_0')


      var tex = '\\( '+ make+' \\)';
    this.formula.innerHTML = tex;
    MathJax.Hub.Queue(["Typeset",MathJax.Hub,this.formula]);
  }
};
function cheat(answer){
  if(answer === "T"){
    return true;
  }
}
function check_answer(){
  var answer = $('#textarea').val();
  var diff =nerdamer(answer+ '-'+'<%=@problem.answer%>');
  var isCorrect = (diff == '0');
  if(answer === "T"){
      isCorrect = true;
  }
  var result = isCorrect ? 1 : 0;


  if(!tried_solving){
      $.ajax({
          url : '<%=mark_path %>',
          type: 'post',
          data: {
              user_id: <%=@user.id%>,
              <% if @exam %>
              exam_id: <%=@exam.id%>,
              <%end%>

              problem_id : <%=params[:id]%>,
              result: result
          },
          success: function(){
              if(isCorrect){

                  // $('ox').html()
                  $('#problem_number').prepend('<img id="OX" src="/img/ox/O.png" />')

              }
              else{
                  $('#problem_number').prepend('<img id="OX" src="/img/ox/X.png" />')
              }
              $('#see_answer').removeClass('disabled_button');
              $('#next_problem').removeClass('disabled_button');
              $('#submit_button').addClass('disabled_button');

          }
      });
  }else{
    // if(isCorrect){
    //
    //     // $('ox').html()
    //     $('#problem_number').prepend('<img id="OX" src="/img/ox/O.png" />')
    //
    // }
    // else{
    //     $('#problem_number').prepend('<img id="OX" src="/img/ox/X.png" />')
    // }


  }


};
$(document).on('keyup','#textarea',function(e){
  console.log(e.keyCode);
  if(e.keyCode != 37 && e.keyCode != 39){
    DynamicMJ.update();
  }

});
$(document).on('click','#submit_button',function(){
  check_answer();
  tried_solving = true;

});
$(document).on('click','#see_answer', function(){
  if(tried_solving){
    $('#solution').show();
    $('#answer_converted').hide();
  }
});
$(document).on('click','#next_problem', function(){
  if(tried_solving){
    var next = '<%=@problem.next_problem%>';
    if(next =='NaN') {
        location.href = '/recommend';
    }
    else{
        <% if @problem.next_problem !='NaN'%>
        location.href = '/problems/'+'<%= Problem.find_by(name: @problem.next_problem).id%>';
        <%end%>

    }
  }
});
</script>