config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'welcome/index'
  root 'welcome#index'
  concern :partable do
    resources :parts
  end
  resources :users do
    resources :exams do
      resources :subjects do
        resources :chapters do


        end
      end
    end

  end
  resources :patterns, concerns: :partable

  resources :problems, concerns: :partable
  get '/debugs' , to:"debugs#index"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'problemsfront' => 'problems#front'
  post 'mark' => 'problems#mark', as:'mark'
  get 'list' => 'list#index'
  get 'list2' => 'list#index2'
  get 'list3' => 'list#index3'
  get 'list4' => 'list#index4'
  get 'list5' => 'list#index5'
  get 'list6' => 'list#index6'
  get 'tree' => 'list#tree'
  get 'levels' => 'levels#index'
  post '/exam_update' => 'debugs#update', as: 'exam_update'
  post '/exam_generate' => 'debugs#generate', as: 'exam_generate'
  post '/exam_destroy' => 'debugs#destroy', as: 'exam_destroy'
  get '/status' => 'debugs#status'
  get '/start/:selected_test_id' =>'problems#set', as: 'exam_start'
  get '/recommend' =>'problems#recommend'
  get '/solution' =>'debugs#solution'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :groups
  belongs_to :subject

end

app/models/dic_chapter.rb
class DicChapter < ApplicationRecord
  has_many :dic_groups
  belongs_to :dic_subject
end

app/models/dic_group.rb
class DicGroup < ApplicationRecord
  belongs_to :dic_chapter
end

app/models/dic_subject.rb
class DicSubject < ApplicationRecord
  has_many :dic_chapters

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :subjects
  belongs_to :user
  has_many :meters
  has_many :history_problems





end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :chapter
end

app/models/history_problem.rb
class HistoryProblem < ApplicationRecord
  belongs_to :exam
end

app/models/last_exam.rb
class LastExam < ApplicationRecord
  belongs_to :user
end

app/models/meter.rb
class Meter < ApplicationRecord
  belongs_to :exam

  def set_score(diff)
    if(self.sign == 0 )
      self.sign = diff
      self.combo =1
    elsif self.sign*diff>0
      self.combo *= 1.25
    else
      self.combo =1
      self.sign =diff
    end

    self.score += 0.7*self.combo*diff

    if(self.score>5)
      self.score =5
    elsif self.score <-5
      self.score = -5
    end
    self.save
    self.exam.save


  end
  def first
    return self
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :pattern
  belongs_to :problem
end

app/models/pattern.rb
class Pattern < ApplicationRecord

  has_many :parts
  has_many :problems, through: :parts


end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :parts
  has_many :patterns, through: :parts


end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :chapters
  belongs_to :exam


end

app/models/user.rb
class User < ApplicationRecord
  has_many :exams
  validates :username, presence:true, uniqueness: true
  validates :password, presence:true
  validates :password_confirmation, presence: true
  has_secure_password
  has_one :last_exam


  def set_last_exam(id)
    self.last_exam=id
    self.save

  end

  def generate_exam()


    new_exam = Exam.new(user: self, name: '새로운 시험')

    self.exams << new_exam
    dic_subjects=DicSubject.all
    dic_subjects.each do |dic_subject|
      subject = Subject.create(name: dic_subject.name, exam: new_exam,onStudy: 0, onExam: 0)

      dic_subject.dic_chapters.each do |dic_chapter|
        chapter = Chapter.create(name:dic_chapter.name, subject: subject, onStudy:0, onExam:0, level:0)

        dic_chapter.dic_groups.each do |dic_group|
          group = Group.create(name:dic_group.name, chapter:chapter, level:0)

        end
      end
    end





    new_exam.save

    self.save
  end



 end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end



end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/debugs_helper.rb
module DebugsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
  def index
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/index.html.erb
<h2>users list</h2>
<% @users.each do |user| %>
    <div>
      <p><%=user.username %></p>
      <% user.exams.each do |exam| %>
        <div>
          <p>&emsp;<%= exam.name %></p>
          <%= link_to "view problems",user_exam_path(user,exam) %>
          <% exam.subjects.each do |subject| %>
            <div>
              <p> &emsp;&emsp;<%=subject.name%> <%=subject.check%></p>
              <% subject.chapters.each do |chapter| %>
                <div>
                  <p>&emsp;&emsp;&emsp;<%=chapter.name %> <%= chapter.check %></p>

                </div>
              <%end %>
            </div>
          <% end %>
        </div>

      <% end%>
    </div>
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  </head>
  <body style="background-color: #d8f4ff">


    <div class="container center-align row flow-text">
      <a href="/"><img src="img/logos/login_logo.png" alt="logo_front" style="width:9vw; margin:2%;"></a>
      <div class="submit_form col s10 offset-s1">
        <div class="left-align" style="margin-left: 5%;"><a href="login" style="color: inherit; font-size: 1em;" class="align-left" >로  그  인</a></div>
        <%= form_for(@user) do |f| %>
        <div><%= f.text_field :username, :placeholder => "id",id:"submit_space"%></div>
        <div><%= f.password_field :password, :placeholder => "Password", id:"submit_space"%></div>
        <div><%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", id:"submit_space"%></div>
        <%= f.submit "회  원  가  입", id: "submit_button" %>
      <% end %>
      </div>
    </div>


  </body>
</html>


<!-- stylesheet -->
<style media="screen">
#submit_space {
  height: auto;
  width: 85%;
  background-color: white;
  /*display: inline-block;*/
  padding: 2%;
  margin: 1%;
  font-size: 32px;
  color: black;
  border-radius: 10px;
  box-shadow: 5px 5px #02aad1;
  text-overflow: ellipsis;
}
#submit_space:hover {box-shadow:5px 5px #00008B;}

#submit_button {
  display: inline-block;
  /*padding: 5px 420px ;*/
  width: 90%;
  padding: 2%;
  font-size: 110%;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #02aad1;
  border: none;
  border-radius: 10px;
  box-shadow: 5px 5px #999;
  margin: 3%;
}

#submit_button:hover {background-color: #00008B;box-shadow: 5px 5px #02aad1;}
</style>